apiVersion: v1
kind: Secret
metadata:
  name: db-cred
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: back-config
data:
  DB_URL: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: collinskube-back
spec:
  ports:
  - name: collinskube-back
    port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: back

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collinskube-back
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: collinskube-back
        image: xzjia/collinskube-back:0.1
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: password
        readinessProbe:
          httpGet:
            path: /view-api/actuator/health
            port: server-port
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - name: server-port
          containerPort: 8090