apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: collinskube.com
    http:
      paths:
      - path: /
        backend:
          serviceName: collinskube-front
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: collinskube-front
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: front

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collinskube-front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: collinskube-front
        image: xzjia/collinskube-front:0.1
        ports:
        - containerPort: 80