apiVersion: v1
kind: Service
metadata:
  name: collinskube-register-consumer
spec:
  type: LoadBalancer
  ports:
  - name: collinskube-register-consumer
    port: 80
    targetPort: 8070
    protocol: TCP
  selector:
    app: register-consumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collinskube-register-consumer
  labels:
    app: register-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-consumer
  template:
    metadata:
      labels:
        app: register-consumer
    spec:
      containers:
      - name: collinskube-register-consumer
        image: xzjia/collinskube-register-consumer:0.1
        env:
        - name: KAFKA_BROKER
          value: "infra-cp-kafka"
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: password
        ports:
        - name: server-port
          containerPort: 8070